name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout del codice sorgente
        uses: actions/checkout@v3

      - name: Configura JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      - name: Scansione vulnerabilità del codice
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
#acs-report-enable: true

      - name: Carica il report delle vulnerabilità
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Build, test unitari e test di integrazione
        run: |
          mvn -X clean verify

      - name: Riepilogo test unitari
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Unit Test Report
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false

      - name: Riepilogo test di integrazione
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Integration Test Report
          path: target/failsafe-reports/*.xml
          reporter: java-junit
          fail-on-error: false

      - name: Salva risultati dei test
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: risultati-test
          path: |
            target/surefire-reports/
            target/failsafe-reports/